### ISSUE TITLE
angles->dir with axis selection.

### ISSUE THREAD

**Issue by ABOS80** [jeapostrophe/pict3d#12]
Hello.
angles->dir yaw around z and rotates around x, i would like to shoose the yaw/roll axis.

Something like:
(angles->dir yaw roll #:yaw z #:roll y)

Hope itd not to complicated.

**Comment by ABOS80** [comment]
Found the function and started exploring.
Making it yaw around z from y and roll around y wasnt that hard, I'm going to implement more.

**Comment by jeapostrophe** [comment]
Excellent. Keep me posted and submit a pull request

**Comment by ABOS80** [comment]
I've mad a function called "angles->dir-yr", yr is for yaw roll. You call it like (angles->sir-yr 0 90 "zy") I wonder if a strong is appropriate or if there is a better way... maybe symbols.

I have implemented six types of yaw roll about different axis, although I need to run som tests before I do a pull request.

**Comment by jeapostrophe** [comment]
In this case, a symbol is more likely to be the standard. Or a bunch of different functions.

**Comment by ABOS80** [comment]
I spotted a mistake in the description of "angles->dir". It says yaw is rotation about z axis and pitch is a rotation about x axis, that can't be. Given "0 0" you get +x so a rotation about the x axis would also result in +x but it results in +z meaning pitch must be around the y axel. Time to debug the scribble.

**Comment by ABOS80** [comment]
Also there isn't any order, yaw and pitch is just calculated. The only time when you need an order is when you rotate an object around all axis meaning roll yaw pitch in that order.

**Comment by ABOS80** [comment]
And one other thing, Pict3D use a righthanden coordinate system. So rotating(pitch) around y from x should point at -z not z because you go counterclockwise with a positive angle. Correct me if I'm wrong.

**Comment by ABOS80** [comment]
You can close this issue, I'll try change things that's wrong and send a pull request.

**Comment by jeapostrophe** [comment]
Ok! I'll wait the PR.
