### ISSUE TITLE
Camera/view transformation?

### ISSUE THREAD

**Issue by ABOS80** [jeapostrophe/pict3d#13]
I've been looking around the code to se how the camera/view is handled. I found camera.rkt but it doesn't tell the hole story. I would like to have a camera object that takes values that describes how to move the world around the camera, meaning move the world(dx dy dz) and rotate world(pitch->yaw->rotate).

**Comment by jeapostrophe** [comment]
I think you are looking for the 'camera basis or `current-pict3d-auto-camera`, which is built by constructing an affine transformation.

**Comment by ABOS80** [comment]
So the 'camera tag only tells pict3d its a camera transformation? Another trouble im having is turning the camera/view up/down(pitch) more than 90 degrees with a dir, look at my little spaceflight program, try turn straight down... something is wrong... maybe its me.

https://github.com/APOS80/SpaceFlight/

**Comment by ABOS80** [comment]
Ah, got it... it's the angle again.
