### ISSUE TITLE
About rotation 

### ISSUE THREAD

**Issue by ABOS80** [jeapostrophe/pict3d#17]
I've made a quaternion module that works well and with ease avoids gimbal-lock. Even though it's okay to have it as a separate module it would be easier to use if it was a part of Pict3D and could use the structures already there. I've made a small flying in space demo that you can try. If there's an interest I can make a Pict3D version and do a PR.

**Comment by ABOS80** [comment]
https://github.com/APOS80/SpaceFlight

**Comment by jeapostrophe** [comment]
My assumption is that Neil would expect you to use math/matrix and math/array for the quaternion operations.

**Comment by ABOS80** [comment]
I’m thinking of a procedure taking an (affine dx dy dz pos) , pitch/yaw/roll angles and a length and gives a new affine.

**Comment by ABOS80** [comment]
Oops affine is a procedure so that won’t work, but but given three dir’s and a speed work the same way.

**Comment by ABOS80** [comment]
I’ll try implementing it on my branch and you can pull it in if you like it.
