### ISSUE TITLE
No way to turn off surface data HUD

### ISSUE THREAD

**Issue by dented42** [jeapostrophe/pict3d#22]
When mousing over an object, the HUD in the repl snip displays position and direction information in the bottom right corner. This seems to be expensive and greatly lowers the frame rate when moving the camera, especially compared to when the mouse position is over empty space in the scene.

It seems like there should be a parameter and keyboard shortcut to turn this off and on, for when one just wants to zoom around the scene smoothly without caring about exactly what polygon is under the mouse.

**Comment by jeapostrophe** [comment]
I plan on working on this in the 1 to 2 week time range.

**Comment by jeapostrophe** [comment]
I've looked into this issue more. The HUD only appears when you are viewing a snip, which is the debugging interface. If you want to use `pict3d` for performance rendering, then you want `pict3d-canvas%` or `big-bang3d`.

I did look into turning off the HUD in the snips, but it would require a lot of refactoring.

**Comment by dented42** [comment]
I might take a look and see if I can come up with something. If I come up with something that isn't too disgusting is this an issue you might consider reopening?

**Comment by jeapostrophe** [comment]
Absolutely!

On Sun, Jan 27, 2019 at 6:41 PM dented42 <notifications@github.com> wrote:
>
> I might take a look and see if I can come up with something. If I come up with something that isn't too disgusting is this an issue you might consider reopening?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
-=[     Jay McCarthy               http://jeapostrophe.github.io    ]=-
-=[ Associate Professor        PLT @ CS @ UMass Lowell     ]=-
-=[ Moses 1:33: And worlds without number have I created; ]=-
