### ISSUE TITLE
FFI needs adaptation for CS

### ISSUE THREAD

**Issue by mflatt** [jeapostrophe/pict3d#25]
The GL bindings in "typed/opengl/generated/gl_specs.inc" include types like `(_vector i _string*/utf-8)`. Unfortunately, that type can't work for CS in the same way as BC. Even more unfortunately, the history is

* v8.0 CS: a bug in allocating `(_vector i _string*/utf-8)` made it appear to work, as long as you're not unlucky about GC timing, because it would allocate an atomic array to hold pointers to the converted strings.
* v8.1 CS: the allocation problem was fixed, but then you have a non-atomic pointer being passed to a foreign function, and that doesn't work (because the references to GCable objects are tagged, so nonsense to C); unfortunately an intended check to disallow that was missing, so the nonsense pointer flows through and a crash is inevitable.
* v8.1.0.5: the check is in place, so now something like `(pict3d->bitmap (sphere origin 1/2))` reports an error.

One possible solution is to replace `(_vector i _string*/utf-8)` with

```
(require ffi/unsafe/string-list)
(define _vector-of-string*/utf-8
  (make-ctype _string-list/utf-8 vector->list list->vector))
```

Although I can imagine changing `ffi/unsafe` so that `_vector` and `_list` treat `_string*/utf-8` and related element types specially, I’m not sure that hiding the general issue like that is a good idea. In particular, it looks like `(_vector i _pointer/intptr)` will have the same problem; a `_vector-of-pointer/intptr` type can fix the problem by building on `_bytes-list`, but `_vector` can't auto-correct that case.

**Comment by mflatt** [comment]
New thought: Maybe adjusting `_vector` and `_list` is the right idea, but not based on the element ctype passed to the constructor. Instead, the converter for those forms could dynamically detect that GCable pointers are provided as the array elements, and then it could do something different with the pointers or their contents. If something along those lines works, then no changes would be needed in pict3d after all. I'll experiment more.

**Comment by jeapostrophe** [comment]
I don't feel like I have enough insight to really comment on what the best thing to do is. Perhaps the best thing would be to switch to the `opengl` package that generates these bindings also and if it is doing the wrong thing, fix it in that one place

**Comment by mflatt** [comment]
Every workaround to the CS constraint that I've considered seems to be painful and incomplete. It looks like it will work to instead add non-atomic memory as a concept to Chez Scheme. I've found an approach that adds only a little complexity to Chez Scheme, removes move complexity than that from the Rumble layer, and makes CS and BC the same for this part of the FFI.
